name: MineResetLite
version: 0.2.0
main: com.koletar.jj.mineresetlite.MineResetLite
authors: [jjkoletar, sarhatabaot]
description: A lightweight solution for Mine management.
softdepend: [Multiverse-Core, WorldGuard, WorldEdit, PlaceholderAPI]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.