name: MineResetLite
version: $version$
main: com.koletar.jj.mineresetlite.MineResetLite
authors: [jjkoletar, sarhatabaot]
description: A lightweight solution for Mine management.
softdepend: [Multiverse-Core, WorldGuard, WorldEdit]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.